language: node_js
node_js: 12
matrix:
  fast_finish: true
  include:
  - os: osx
    osx_image: xcode10.2
  - os: linux
    env:
    - CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
    addons:
      apt:
        packages:
        - python3
        - python3-pip
        - python3-setuptools
        - libxkbfile-dev
        - libx11-dev
        - p7zip-full
cache: yarn
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo snap install snapcraft --classic; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "$SNAP_TOKEN" | snapcraft login --with -; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install p7zip; fi
before_script:
- npm install -g npx
- yarn template:install
- yarn lint
script:
- yarn dist
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then yarn catalog:install && yarn catalog:test; fi
- if [ "$TRAVIS_OS_NAME" == "linux" -a "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then yarn
  catalog:install && yarn catalog:pack && yarn catalog:publish; fi
notifications:
  email: false
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: s3.getwebcatalog.com
  local-dir: catalog/dist
  upload-dir: apps
  acl: public_read
  skip_cleanup: true
  on:
    repo: quanglam2807/webcatalog
    condition: $TRAVIS_OS_NAME = linux
branches:
  only:
    - master
    # Ruby regex to match tags. Required, or travis won't trigger deploys when
    # a new tag is pushed. Version tags should be of the form: v0.1.0
    - /^v\d+\.\d+\.\d+.*$/