name: macOS

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
    paths-ignore:
      - 'catalog/**'
      - 'docs/**'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
        submodules: false
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn
    - run: yarn template:install
    - run: yarn lint
    - run: brew install p7zip
    - name: Get tag name
      run: echo ::set-env name=CI_BUILD_TAG::${GITHUB_REF/refs\/tags\//}
      if: startsWith(github.ref, 'refs/tags/')
    - run: yarn dist
      env:
        CI: true
        CI_PULL_REQUEST: ${{ github.event_name == 'pull_request' }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
        CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        CSC_LINK: ${{ secrets.CSC_LINK }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REACT_APP_LICENSE_SECRET: ${{ secrets.REACT_APP_LICENSE_SECRET }}
    - name: Update Homebrew Cask
      # GitHub Actions set HOMEBREW_NO_AUTO_UPDATE=1 by default
      # So `brew update` needs to be run manually
      run: |
        brew update
        brew install vitorgalvao/tiny-scripts/cask-repair
        (cd $(brew --repository) && hub issue)
        cask-repair --cask-version $(node -p -e "require('./package.json').version") --blind-submit webcatalog
      env:
        GITHUB_USER: quanglam2807
        # GitHub Actions secrets.GITHUB_TOKEN only has access to this repo.
        # Use standard access token (https://github.com/settings/tokens)
        # to access quanglam2807/homebrew-cask
        # https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token
        GITHUB_TOKEN: ${{ secrets.MASTER_GITHUB_TOKEN }}
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'